server:
  port: 8091
  mode: debug

database:
  driver: postgres
  postgres_dsn: "host=127.0.0.1 user=usercore password=YOUR_PASSWORD dbname=usercore port=5432 sslmode=disable TimeZone=Asia/Shanghai"

jwt:
  secret: "change-me-in-production-use-long-random-string"
  access_ttl_minutes: 120
  refresh_ttl_hours: 168

cors:
  allow_origins:
    - "http://localhost:5174"
    - "http://127.0.0.1:5174"
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://localhost:5175"
    - "http://127.0.0.1:5175"
    - "http://localhost:5176"
    - "http://127.0.0.1:5176"
    - "http://localhost:5178"
    - "http://127.0.0.1:5178"
    - "http://localhost:5179"
    - "http://127.0.0.1:5179"
    - "http://localhost:5180"
    - "http://127.0.0.1:5180"
    - "http://localhost:5181"
    - "http://127.0.0.1:5181"
    - "http://localhost:5182"
    - "http://127.0.0.1:5182"
    - "http://localhost:5183"
    - "http://127.0.0.1:5183"
    - "http://localhost:5184"
    - "http://127.0.0.1:5184"

apps:
  productcore_url: "http://localhost:5173"
  supplycore_url: "http://localhost:5175"
  aftersalescore_url: "http://localhost:5176"
  storecore_url: "http://localhost:5179"
  storesyncagent_url: "http://localhost:5178"
  warehousecore_url: "http://localhost:5180"
  shippingcore_url: "http://localhost:5181"
  ordercore_url: "http://localhost:5182"
  customercore_url: "http://localhost:5183"
  mallcore_url: "http://localhost:5184"
